# Generated by Django 3.0.7 on 2020-06-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('emailID', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
